title: Balena OpenSprinkler Node-Red
description: Multi-Container build for the opensprinkler firmware and Node-Red
logo: docs/assets/balena-opensprinkler-node-red.png
show_downloads: true
theme: jekyll-theme-minimal