version: '2'
services:
  opensprinkler:
    build: ./opensprinkler
    devices:
     # - "/sys:/sys"
      - /dev/gpiomem:/dev/gpiomem
    cap_add:
      - SYS_RAWIO
    ports:
      - 80:8080

volumes:
  opensprinkler:
  