version: '2'
services:
  opensprinkler:
    build: ./opensprinkler
    devices:
     # - "/sys:/sys"
      - /dev/gpiomem:/dev/gpiomem
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.resin.features.kernel-modules: '1'
    ports:
      - 80:8080

volumes:
  opensprinkler:
  